### ISSUE TITLE
Error with clblast_tuner_xgemm: Exception caught with status -2040 while running the reference

### ISSUE THREAD

**Issue by byeongkyoCheong** [CNugteren/CLBlast#353]
Hi, I'm trying to tune the library for the Odroid-XU4 board and I get the following error when I run the ./clblast_tunner_xgemm -m 173056 -k 64 -n 128 -alpha 1.0 -beta 0.0

the tuner runs well in 1 and 2 stanges.

Any ideas about the error and/or how to solve it? Thanks.

![image](https://user-images.githubusercontent.com/32692344/56255202-eb784c00-60fe-11e9-832e-335905146bb7.png)

**Comment by CNugteren** [comment]
Thanks for reporting. I'll have a look soon.

**Comment by CNugteren** [comment]
I can't reproduce it myself yet. Could you compile the `clblast_test_preprocessor` test and run it, to see if it also fails? If so, please do post the output here.

**Comment by byeongkyoCheong** [comment]
I compiled and ran the `clblast_test_preprocessor` you mentioned and It passed all the tests.

**Comment by CNugteren** [comment]
Thanks for running. Actually, I see 13 tests myself, which includes a second `Xgemm` test that does test the code you the error in. And that runs fine, because that issue is resolved already :-) The changelog [shows this in line 14](https://github.com/CNugteren/CLBlast/blob/master/CHANGELOG#L14). So just an update to the latest version should fix it for you :-)

**Comment by byeongkyoCheong** [comment]
Thanks for answering👍. But the tuner still fails in 3 and 4 stages for the same parameters. I updated the library to version 1.5.0 which is the latest. I also compiled and executed `clblast_test_preprocessor` and it passed all the tests. 

```
* (3/4) Tuning secondary GEMM kernel (GEMMK == 1) for fixed set of parameters

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -m 173056
    -n 128
    -k 64
    -alpha 1.00
    -beta 0.00
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Found 407 configuration(s)
* Parameters explored: GEMMK MWG NWG KWG MDIMC NDIMC MDIMA NDIMB KWI VWM VWN STRM STRN SA SB KREG

|   ID | total |                                                                           param |       compiles |         time | GFLOPS |            status |
x------x-------x---------------------------------------------------------------------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                                                                               - |             OK |  error -14   |      - |* Exception caught with status -2040 while running the reference, aborting
* (4/4) Tuning secondary GEMM kernel (GEMMK == 1) for random parameters out of larger set

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -m 173056
    -n 128
    -k 64
    -alpha 1.00
    -beta 0.00
    -fraction 128.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Found 15910 configuration(s)
* Exploring a random subset of 124 configuration(s)
* Parameters explored: GEMMK MWG NWG KWG MDIMC NDIMC MDIMA NDIMB KWI VWM VWN STRM STRN SA SB KREG

|   ID | total |                                                                           param |       compiles |         time | GFLOPS |            status |
x------x-------x---------------------------------------------------------------------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                                                                               - |             OK |  error -14   |      - |* Exception caught with status -2040 while running the reference, aborting

```

**Comment by CNugteren** [comment]
Yes, OK, but that's a entirely different issue now then :-) The tuner first runs a reference implementation, which is assumed to always work (not the case for 100% of the devices out there though).

First question would be: you are giving custom m/n/k sizes and such, does the tuner work fine with the default arguments? Second question would be - if that also fails - could you post the output of `clinfo` for the Mali GPU (I presume?) you are running on. Otherwise I would just say to ignore that part of the tuning and hope that the first 2 stages gave you a good result already :-)

**Comment by byeongkyoCheong** [comment]
OK, thank you for your help! the tuner works fine with the default arguments so well. So I'll use the results of the first 2 stages as you said because there is no problem at all!
