### ISSUE TITLE
Does CLBlast supports opencl 1.1 EP

### ISSUE THREAD

**Issue by Mezzano** [CNugteren/CLBlast#88]
I'm wondering if the Embedded Profile is supported as I get a [floating point exception](https://github.com/rickyHong/caffe-for-clblast-branch/issues/1) when trying to run in GPU mode.

**Comment by CNugteren** [comment]
I am not sure if there are any limiting features in CLBlast. Could you run the included tests and tell me which ones fail/succeed?

**Comment by dvasschemacq** [comment]
Hi, I'm working with Mezzano, we were able to run the test now, we tried this one : clblast_test_xsyr

And the output is `* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'SSYR' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
   - -> Test not completed: Reference CBLAS doesn't output error codes
* Testing 'regular behaviour' for '101 (row-major) 121 (upper)':
   OpenCL compiler error/warning: (358:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (358:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (358:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (358:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (358:0) : error : syntax error at '__kernel'

....
....
....

   Pass rate   0.0%: 0 passed / 12 skipped / 0 failed
* Completed all test-cases for this routine. Results:
   0 test(s) passed
   48 test(s) skipped
   0 test(s) failed

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'DSYR' routine.
* All tests skipped: Unsupported precision

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'HSYR' routine.
* All tests skipped: Unsupported precision
`

So there seems to be a precision problem that can come from the EP we have. 

But will it block the working of the library, I don't think, normally it should work but with less precision due to our hardware? Is it right?

**Comment by CNugteren** [comment]
The precision is automatically detected by CLBlast. That's why it is running the tests for `SSYR` but not for `DSYR`. However, the tests for single-precision (`SSYR`) are failing, because the OpenCL compiler cannot successfully compile the kernel. It gives this error:
```
-OpenCL compiler error/warning: (358:0) : error : syntax error at '__kernel'
```
That's not a lot of information for me unfortunately.

Could you try another test, preferably one with a simpler kernel, say one of `xswap`, `xscal`, `xcopy` or `xaxpy`?

**Comment by dvasschemacq** [comment]
Actually there are no more information about the error. I tried to run the test you said, we have the same error. I paste here the output for xswap : 

`imx6demo:~/CLBlast/build # ./clblast_test_xswap 

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -full_test [false]
    -verbose [false]
    -cblas 1 [=default]

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'SSWAP' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
   - -> Test not completed: Reference CBLAS doesn't output error codes
* Testing 'regular behaviour' for 'default':
   OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-
   Pass rate   0.0%: 0 passed / 27 skipped / 0 failed
* Completed all test-cases for this routine. Results:
   0 test(s) passed
   27 test(s) skipped
   0 test(s) failed

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'DSWAP' routine.
* All tests skipped: Unsupported precision

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'CSWAP' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
   - -> Test not completed: Reference CBLAS doesn't output error codes
* Testing 'regular behaviour' for 'default':
   OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-OpenCL compiler error/warning: (338:0) : error : syntax error at '__kernel'

-
   Pass rate   0.0%: 0 passed / 27 skipped / 0 failed
* Completed all test-cases for this routine. Results:
   0 test(s) passed
   27 test(s) skipped
   0 test(s) failed

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'ZSWAP' routine.
* All tests skipped: Unsupported precision

* Running on OpenCL device 'Vivante OpenCL Device'.
* Starting tests for the 'HSWAP' routine.
* All tests skipped: Unsupported precision

`

There seems to be an error with the syntax of the kernel file, but we haven't touched it. Could it be some compatibility problem with our compiler? Or maybe the CL compiler (which is ?)...
We are using GCC 4.8.5. What we have changed in the compilation is that the optimization option is set to `-O0`, otherwise GCC is stuck on the compilation of the file database.cpp on armv7hl (not on x64).

**Comment by CNugteren** [comment]
This is not related to GCC, it is the Vivante OpenCL compiler not able to handle the CLBlast sources. There is something in the sources apparently that it doesn't like, not sure what though, the error message is not really helpful.

Perhaps it doesn't support the `__attribute__` construct? Can you perhaps comment those lines out in all the OpenCL kernel sources files?

**Comment by dvasschemacq** [comment]
We fixed the issue using another OpenCL compiler from Vivante and by moving the __kernel kerword before the __attribute__. 
It seems that it is defined this way in the example from OpenCL 1.1 from Khronos and that solved the syntax error with the vivante compuler.

**Comment by CNugteren** [comment]
Indeed, it seems that this is the proper way. Interesting to see that all the OpenCL compilers I tested on also accepted `__attribute__` before `__kernel`. Thank you for the pull request. I will accept it and test it on a couple of systems to be sure that other compilers also accept this ordering.

Reference:
https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/functionQualifiers.html

**Comment by Mezzano** [comment]
Hello,

we still don't have all tests passing:

[https://gist.github.com/Mezzano/bdc82b40374bbdc574045c640b8422d6](https://gist.github.com/Mezzano/bdc82b40374bbdc574045c640b8422d6)

./clblast_test_xgemm specifically:

[https://gist.github.com/Mezzano/f0e10bdd3e908f2196d490b15c097735](https://gist.github.com/Mezzano/f0e10bdd3e908f2196d490b15c097735)

It gives us:

`[galcore]: GPU[0] hang, automatic recovery.`

Any idea, why?

**Comment by CNugteren** [comment]
So for GEMM it seems that SGEMM works fine but CGEMM doesn't? Perhaps the complex version is using too many registers? One thing I suggest before you continue is to run the tuners. That way it finds a configuration that is fast but also correct. If you can post the JSON output to GitHub that would be great; I'll incorporate it in the next release.

For the other failing tests, can you get the full output from CTest for me? Or otherwise (much easier), just run the individual tests like you did for `clblast_test_xgemm`?

**Comment by dvasschemacq** [comment]
This is the output of the test `clblast_test_xgemm` :

'-OpenCL compiler error/warning: (553:0) : error : syntax error at '{'
(554:0) : error : syntax error at '{'
(555:0) : error : syntax error at '{'
(556:0) : error : syntax error at '{'
(1501:0) : error : function: 'InitAccRegisters' hasn't the corresponding declaration
(1546:0) : error : function: 'MultiplyAccumulate' hasn't the corresponding declaration
(1674:0) : error : function: 'XgemmBody' hasn't the corresponding declaration
(1678:0) : error : function: 'StoreResults' hasn't the corresponding declaration'

**Comment by CNugteren** [comment]
I'm closing this issue now: the original question is answered.

The other compilation issue you mentioned is further discussed in #91.
